// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvNR1zXyk2oG1R0JJDYrzw9eRtnUU5NFQ',
    appId: '1:476996817016:android:bc004ae7f415f1b2da9d8d',
    messagingSenderId: '476996817016',
    projectId: 'krishnaversee-10fc7',
    storageBucket: 'krishnaversee-10fc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_1hyts6F5vi6OL7sNwK0Mjc7BKFv2Vco',
    appId: '1:476996817016:ios:b3ebf188b6d9afcfda9d8d',
    messagingSenderId: '476996817016',
    projectId: 'krishnaversee-10fc7',
    storageBucket: 'krishnaversee-10fc7.firebasestorage.app',
    androidClientId: '476996817016-klei8l55gp9rrfe3i6gb73490sljruf3.apps.googleusercontent.com',
    iosClientId: '476996817016-9h7tq9vtennonqgl6n8pptov6d7p6jc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishnaversee',
  );
}
